import { promises as fs } from 'node:fs';
import path from 'node:path';
import { Inject, Injectable } from '@nestjs/common';
import { findRepoRoot } from '@victorflow/db';
import { APP_CONFIG, type AppConfig } from '../../config/config';

/**
 * File storage abstraction. The MVP writes to the local filesystem; anything that speaks this interface
 * (an S3-compatible bucket, say) can replace it without touching callers.
 * MVP-NOTE: no MinIO/S3 in the MVP by design — swap the provider in StorageModule when you need it.
 */
export abstract class StorageService {
  abstract put(key: string, data: Buffer): Promise<void>;
  abstract get(key: string): Promise<Buffer>;
  abstract exists(key: string): Promise<boolean>;
  abstract delete(key: string): Promise<void>;
}

@Injectable()
export class LocalStorageService extends StorageService {
  private readonly root: string;

  constructor(@Inject(APP_CONFIG) config: AppConfig) {
    super();
    // Relative STORAGE_DIR (./storage) resolves from the monorepo root, not from whichever cwd started the process.
    this.root = path.isAbsolute(config.storageDir) ? config.storageDir : path.resolve(findRepoRoot(), config.storageDir);
  }

  /** Keys are generated by the server, but never trust a path: refuse anything that resolves outside the root. */
  private resolve(key: string): string {
    if (!key || key.includes('\0')) throw new Error('Invalid storage key');
    const full = path.resolve(this.root, key);
    const rel = path.relative(this.root, full);
    if (rel.startsWith('..') || path.isAbsolute(rel)) throw new Error('Storage key escapes the storage root');
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const full = this.resolve(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    // write-then-rename so a crash never leaves a half-written file under the final name
    const tmp = `${full}.${process.pid}.${Date.now()}.${Math.random().toString(36).slice(2)}.tmp`;
    await fs.writeFile(tmp, data, { flag: 'wx' });
    try {
      await fs.rename(tmp, full);
    } catch (err) {
      // Windows refuses to rename over an existing file in some cases (EPERM/EEXIST/EBUSY). Replace explicitly.
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== 'EPERM' && code !== 'EEXIST' && code !== 'EBUSY') {
        await fs.rm(tmp, { force: true });
        throw err;
      }
      try {
        await fs.rm(full, { force: true });
        await fs.rename(tmp, full);
      } catch (retryErr) {
        await fs.rm(tmp, { force: true });
        throw retryErr;
      }
    }
  }

  // async, so an invalid key is a rejected promise like every other failure — never a synchronous throw
  async get(key: string): Promise<Buffer> {
    return fs.readFile(this.resolve(key));
  }

  async exists(key: string): Promise<boolean> {
    const full = this.resolve(key); // an escaping key throws, like put/get/delete — it is a bug or an attack, not "absent"
    try {
      await fs.access(full);
      return true;
    } catch {
      return false;
    }
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.resolve(key), { force: true });
  }
}
